### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups' (another incarnation)

### ISSUE THREAD

**Issue by jaroslawhartman** [jaroslawhartman/withings-garmin-v2#4]
Garmin has changed something again, between 10th and 11th of May.... Issue similar to https://github.com/jaroslawhartman/withings-garmin-v2/issues/2

```
Traceback (most recent call last):
  File "/home/jhartman/scripts/withings-garmin-v2/sync.py", line 126, in <module>
    main()
  File "/home/jhartman/scripts/withings-garmin-v2/sync.py", line 59, in main
    sync(**opts.__dict__)
  File "/home/jhartman/scripts/withings-garmin-v2/sync.py", line 118, in sync
    session = garmin.login(garmin_username, garmin_password)
  File "/home/jhartman/scripts/withings-garmin-v2/garmin.py", line 139, in login
    session = self._get_session(email=username, password=password)
  File "/home/jhartman/scripts/withings-garmin-v2/garmin.py", line 77, in _get_session
    data["lt"] = re.search("name=\"lt\"\s+value=\"([^\"]+)\"", preResp.text).groups(1)[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by jaroslawhartman** [comment]
Closing

**Comment by agentbond007** [comment]
Thank you. 🏆
